

INSERT INTO DATOSPERSONALES(IDCOLABORADOR,USUARIO,NOMBRE,FECHANACIMIENTO,GENERO,ESTADO,CORREO,TELEFONO,DIRECCION,USUARIOCREACION,USUARIOMODIFICA,FECHACREACION,FECHAMODIFICA)
VALUES(45454545,'JPEREZG','Jose Perez Gonzales','1983-06-11','Masculino','Casado','jperezg@gmail.com','999998752','Av. Jose Galvez 765 Lince - Lima','ADMIN','ADMIN',GETDATE(),GETDATE())
GO

INSERT INTO DATOSPERSONALES(IDCOLABORADOR,USUARIO,NOMBRE,FECHANACIMIENTO,GENERO,ESTADO,CORREO,TELEFONO,DIRECCION,USUARIOCREACION,USUARIOMODIFICA,FECHACREACION,FECHAMODIFICA)
VALUES(54545454,'KGONZALESC','Katia Gonzales Colareta','2000-09-13','Femenino','Soltera','kgonzalesc@gmail.com','989898989','Av. cuba 1289 Jesús Maria - Lima','ADMIN','ADMIN',GETDATE(),GETDATE())
GO



INSERT INTO DEPENDIENTES(IDDEPENDIENTE,IDCOLABORADOR,TIPODEPENDENCIA,NOMBRE,FECHANACIMIENTO,GENERO,ESTADO,USUARIOCREACION,USUARIOMODIFICA,FECHACREACION,FECHAMODIFICA)
VALUES(46464646,45454545,'Esposa','Pilar Villegas Nortel','1985-10-22','Femenino','Casada','ADMIN','ADMIN',GETDATE(),GETDATE())
GO

INSERT INTO DEPENDIENTES(IDDEPENDIENTE,IDCOLABORADOR,TIPODEPENDENCIA,NOMBRE,FECHANACIMIENTO,GENERO,ESTADO,USUARIOCREACION,USUARIOMODIFICA,FECHACREACION,FECHAMODIFICA)
VALUES(47474747,45454545,'Hijo','Alexander Perez Villegas','2014-08-06','Masculino','Soltero','ADMIN','ADMIN',GETDATE(),GETDATE())
GO

INSERT INTO DEPENDIENTES(IDDEPENDIENTE,IDCOLABORADOR,TIPODEPENDENCIA,NOMBRE,FECHANACIMIENTO,GENERO,ESTADO,USUARIOCREACION,USUARIOMODIFICA,FECHACREACION,FECHAMODIFICA)
VALUES(48484848,45454545,'Hija','Claudia Perez Villegas','2016-03-12','Femenino','Soltera','ADMIN','ADMIN',GETDATE(),GETDATE())
GO

INSERT INTO DEPENDIENTES(IDDEPENDIENTE,IDCOLABORADOR,TIPODEPENDENCIA,NOMBRE,FECHANACIMIENTO,GENERO,ESTADO,USUARIOCREACION,USUARIOMODIFICA,FECHACREACION,FECHAMODIFICA)
VALUES(56565656,45454545,'Madre','Maria Colareta Carrales','1972-02-11','Femenino','Viuda','ADMIN','ADMIN',GETDATE(),GETDATE())
GO
