
CREATE PROC USP_ObtenerDatosPersonales
(
	@IDCOLABORADOR BIGINT
)
AS
	SELECT	P.IDCOLABORADOR,
			    P.NOMBRE,
			    P.FECHANACIMIENTO,
			    P.GENERO,
			    P.ESTADO,
			    P.TELEFONO,
			    P.CORREO,
			    P.DIRECCION

	FROM	DATOSPERSONALES P
	WHERE	P.IDCOLABORADOR = @IDCOLABORADOR
GO

CREATE PROC USP_ObtenerDependientes
(
	@IDCOLABORADOR BIGINT
)
AS
	SELECT	P.IDDEPENDIENTE,
			    P.TIPODEPENDENCIA,
			    P.NOMBRE,
			    P.FECHANACIMIENTO,
			    P.GENERO,
			    P.ESTADO
          
	FROM	DEPENDIENTES P
	WHERE	P.IDCOLABORADOR = @IDCOLABORADOR
GO
