
CREATE TABLE DATOSPERSONALES
(
	IDCOLABORADOR       		    BIGINT PRIMARY KEY ,
	USUARIO							        VARCHAR(50),
	NOMBRE                			VARCHAR(256),
	FECHANACIMIENTO					    DATE,
	GENERO			                VARCHAR(50),
	ESTADO               			  VARCHAR(50),
	CORREO							        VARCHAR(256),
	TELEFONO						        VARCHAR(9),
	DIRECCION						        VARCHAR(256),
	USUARIOCREACION        		 	VARCHAR(50),
	USUARIOMODIFICA    				  VARCHAR(50),
	FECHACREACION           		DATETIME,
	FECHAMODIFICA       			  DATETIME
)
GO

CREATE TABLE DEPENDIENTES
(
	IDDEPENDIENTE       		    BIGINT PRIMARY KEY,
	IDCOLABORADOR					      BIGINT,
	TIPODEPENDENCIA             VARCHAR(50),
	NOMBRE 					            VARCHAR(256),
	FECHANACIMIENTO					    DATE,
	GENERO                			VARCHAR(50),
	ESTADO               			  VARCHAR(50),
	USUARIOCREACION        			VARCHAR(50),
	USUARIOMODIFICA    			    VARCHAR(50),
	FECHACREACION           		DATETIME,
	FECHAMODIFICA       			  DATETIME
)
GO
