 
CREATE TABLE DATOSPERSONALES
(
	IDCOLABORADOR       		    BIGINT PRIMARY KEY ,
	USUARIO							        VARCHAR(50),
	NOMBRE                			VARCHAR(256),
	FECHANACIMIENTO					    DATE,
	GENERO			                VARCHAR(50),
	ESTADO               			  VARCHAR(50),
	CORREO							        VARCHAR(256),
	TELEFONO						        VARCHAR(9),
	DIRECCION						        VARCHAR(256),
	USUARIOCREACION        		 	VARCHAR(50),
	USUARIOMODIFICA    				  VARCHAR(50),
	FECHACREACION           		DATETIME,
	FECHAMODIFICA       			  DATETIME
)
GO

CREATE TABLE DEPENDIENTES
(
	IDDEPENDIENTE       		    BIGINT PRIMARY KEY,
	IDCOLABORADOR					      BIGINT,
	TIPODEPENDENCIA             VARCHAR(50),
	NOMBRE 					            VARCHAR(256),
	FECHANACIMIENTO					    DATE,
	GENERO                			VARCHAR(50),
	ESTADO               			  VARCHAR(50),
	USUARIOCREACION        			VARCHAR(50),
	USUARIOMODIFICA    			    VARCHAR(50),
	FECHACREACION           		DATETIME,
	FECHAMODIFICA       			  DATETIME
)
GO


--Tabla de Historico de Periodos del Colaborador
CREATE TABLE TM_COLABORADOR
(
	IDCOLABORADOR			VARCHAR(20) ,
	FECHAALTA				DATE ,
	NOMBRE					VARCHAR(254) NOT NULL,
	APEPARTERNO				VARCHAR(254) NOT NULL,
	APEMARTERNO				VARCHAR(254) NOT NULL,
	FECNACIMIENTO           DATE,
	ESTADO					VARCHAR(1),
	USUARIOCREA				INT,
	USUARIOMODIFICA			INT,
	FECHACREA				DATETIME,
	FECHAMODIFICA			DATETIME,
	CONSTRAINT PK_COLABORADOR PRIMARY KEY (IDCOLABORADOR,FECHAALTA)
)

GO
--Tabla de Historico de vacaciones del Colaborador
CREATE TABLE TM_VACACIONES
(
	IDCOLABORADOR       VARCHAR(20),
	FECHAALTA           DATE,
	PERIODO             INT,
	FECHAINICIO         DATE,
	FECHAFIN            DATE,
	DIAS                INT,
	ESTADO				VARCHAR(1),
	USUARIOCREA         INT,
	USUARIOMODIFICA     INT,
	FECHACREA           DATETIME,
	FECHAMODIFICA       DATETIME,
	CONSTRAINT PK_VACACIONES PRIMARY KEY (IDCOLABORADOR,FECHAALTA,PERIODO,FECHAINICIO)
)

--Tabla de Registro de Descansos Medicos
CREATE TABLE REGISTRO_DESCANDO_MED
(
	IDCOLABORADOR       	INT PRIMARY KEY IDENTITY(1,1),
	FECHA_ATENCION			  DATETIME,
	MOTIVO_DESC				    VARCHAR(256),
	DETALLE_MOTIVO_DESC		VARCHAR(256),
	FECHA_INICIO_DESC		  DATETIME,
	FECHA_FIN_DESC		  	DATETIME,
	CONSTANCIA_DESC_PDF		VARCHAR(256)	
)
GO
